### List all messages

GET http://localhost:3000/messages

### List all messages

POST http://localhost:3000/messages
content-type: application/json

{"content": "hello"}

### Get a messages

GET http://localhost:3000/messages/436


